### ISSUE TITLE
Data load to hive succeeds but I can't run sparql queries against the data

### ISSUE THREAD

**Issue by ilknuricke** [Quetzal-RDF/quetzal#1] opened 2015-07-08 00:47 UTC
Based on the directions on your wiki, I ran runLoadSpark.sh without a problem--I can see the data on hive. However, the rest is not clear.

Your Wiki says:

"Once your dataset is loaded, you can run queries against that dataset from within the container. Use the command quetzal/com.ibm.research.quetzal.core/scripts/run-dir.sh <test dir>, where <test dir> denotes a directory with files that are .sparql files containing queries to run"

I tried this script, however it is throwing an error: "Failed to invoke suite: null pointer exception". Could you please provide more information on how to run the run-dir.sh and example SPARQL queries for the test.nt on spark installation?  

Thank you in advance.

**Comment by ksrinivs64** [comment] 2015-07-08 12:33
Hello, I suspect the issue is that some environment variables are not being set up properly.  We will try and fix this in the next few days and post a comment when its done.

**Comment by ksrinivs64** [comment] 2015-07-21 19:21
Hello, I've added detailed instructions to the getting started spark section and refactored the code to fix the environment issues.  I've also updated to Spark 1.4.  Let me know if it works for you now.

**Comment by ilknuricke** [comment] 2015-07-22 03:15
Hi. I was able to run your example without a problem. I also tried with my own data file which is an .nt file of approximately 1000 rows.  It seems that there is an issue with bulk upload as it is not uploading the whole dataset. I see xxx_subj.primary.load.0, xxx_subj.primary.load.1 and xxx_subj.primary.load.2 files on the /data directory but it looks like only the load.0 is being uploaded on hive and the rest is missing. When I run a count query I only get what is on the load.0 file.

**Comment by ksrinivs64** [comment] 2015-07-22 11:09
Thats odd and is a regression.  Will check it out.

**Comment by ksrinivs64** [comment] 2015-07-22 21:00
Ok, it was a regression.  We were calling cache table after each loading each file into the table, and it looks like in the new version of spark, cache table makes the table read only (all subsequent loads do not occur).  I've tested it now on a 100K triples dataset.  Let me know if it works.

**Comment by ilknuricke** [comment] 2015-07-22 22:33
Thanks! The upload now works for my dataset.

There is also a minor issue with the generated query, which is however definitely not a show-stopper:

My original query is 
PREFIX acme: http://acme.com/
select ?bookId ?authorId 
from http://acme.com/Graph/books/ 
where {?bookId acme:hasAuthor ?authorId } 
order by ?authorId

Translated SQL:
SELECT authorId AS authorId, authorId_TYP AS authorId_TYP, bookId AS bookId FROM (SELECT entry AS bookd, T.val5 AS authorId, T.typ5 
ASauthorId_TYP FROM default.kb_DPH T WHERE (T.prop5 = 'http://acme.com/hasAuthor')) QS0 ORDER BY authorId ASC

why is authorId_TYP  included in the translated SQL? It was not stated in my original sparql query.

**Comment by ksrinivs64** [comment] 2015-07-23 12:16
Hello, we ask about the types of literal values if we cannot infer the type of the object.  We use that to construct Jena results with the right type.  The right interface to look at (I know we print a lot of debugging output right now including the translated sql) is the result set that gets printed out under RESULTS: which uses the CSV formatting of Jena to print it out.

**Comment by ilknuricke** [comment] 2015-07-23 14:07
Hi,
thanks for your response. I run the translated query within hive because the script throws the following exception in a nested manner and does not give me the result to the above query for example.

java.sql.SQLException
    at org.apache.hive.jdbc.HiveBaseResultSet.findColumn(HiveBaseResultSet.java:94)
    at org.apache.hive.jdbc.HiveBaseResultSet.getString(HiveBaseResultSet.java:637)
    at com.ibm.research.rdf.store.jena.impl.DB2ResultSetImpl.nextBinding(DB2ResultSetImpl.java:171)
    at com.hp.hpl.jena.sparql.resultset.ResultSetMem.<init>(ResultSetMem.java:99)
    at com.ibm.rdf.store.sparql11.TestRunner$AbstractEngine.executeWithInternal(TestRunner.java:422)
    at com.ibm.rdf.store.sparql11.TestRunner$AbstractEngine.executeWith(TestRunner.java:399)
    at com.ibm.rdf.store.sparql11.TestRunner$AbstractEngine.execute(TestRunner.java:385)
    at com.ibm.rdf.store.sparql11.TestRunner$AbstractEngine.executeQuery(TestRunner.java:366)
    at com.ibm.rdf.store.sparql11.TestRunner$AbstractEngine.executeQuery(TestRunner.java:348)
    at com.ibm.rdf.store.sparql11.DirectoryDriver$2$1.runTest(DirectoryDriver.java:48)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at junitx.framework.TestSuite.runTest(TestSuite.java:176)
    at junitx.framework.TestSuite.run(TestSuite.java:171)
    at junit.textui.TestRunner.doRun(TestRunner.java:116)
    at junit.textui.TestRunner.start(TestRunner.java:180)
    at junit.textui.TestRunner.main(TestRunner.java:138)

**Comment by ksrinivs64** [comment] 2015-07-23 16:02
Hi that's really interesting -- I'd like to understand where the issue lies.  When you ran the SQL query successfully using Hive, did you use the beeline client that was packaged up in the docker container with spark?  If not, what did you use?  Thanks!

**Comment by ksrinivs64** [comment] 2015-07-23 16:11
Actually would you mind sharing your SPARQL query?

**Comment by ilknuricke** [comment] 2015-07-23 16:34
I use /usr/local/spark/bin/beeline on the command line within the docker
At the beeline command, !connect jdbc:hive2://localhost:10000 root <password>;
then issue the translated SQL query I copied from the output of your script before the exception occurs.

My original query is 
PREFIX acme: http://acme.com/
select ?bookId ?authorId 
from http://acme.com/Graph/books/ 
where {?bookId acme:hasAuthor ?authorId } 
order by ?authorId

Translated SQL:
SELECT authorId AS authorId, authorId_TYP AS authorId_TYP, bookId AS bookId FROM (SELECT entry AS bookd, T.val5 AS authorId, T.typ5 
ASauthorId_TYP FROM default.kb_DPH T WHERE (T.prop5 = 'http://acme.com/hasAuthor')) QS0 ORDER BY authorId ASC

**Comment by ksrinivs64** [comment] 2015-07-23 18:01
Thanks for your help.  In the past, Spark versions seem to be fussy about their case sensitivity in column names, and that fussiness has changed across versions.  I will test if thats the issue.

**Comment by ksrinivs64** [comment] 2015-07-24 14:33
The issue was indeed the case in column names.  I've checked in a fix, in case you would like to use the jena query interface.  I will also generate some more rigorous tests for spark next.

**Closed as completed** 2015-07-28 15:11 UTC
